const CHANGE_GLOBAL_DATA = "CHANGE_GLOBAL_DATA";
const DISPLAY_TABLE = "DISPLAY_TABLE";
const DISPLAY_BAR_HEADER = "DISPLAY_BAR_HEADER";
const ADD_INITIAL_VALUE = "ADD_INITIAL_VALUE";
const ADD_ADVISER_INFO = "ADD_ADVISER_INFO";
const SET_NOTIFICATION_CONTENT = "SET_NOTIFICATION_CONTENT";
const SET_TOAST_MESSAGE = "SET_TOAST_MESSAGE";
const CHANGE_ADIVSER_FORM = "ADD_ADVISER_FORM";
const CHANGE_SEARCH_FORM = "CHANGE_SEARCH_FORM";
const SET_CLOUD_PROFILE_DATA = "SET_CLOUD_PROFILE_DATA";
const SET_BILLING = "SET_BILLING";
const SET_ACCOUNT_STATUS = "SET_ACCOUNT_STATUS";

export {
    DISPLAY_TABLE,
    CHANGE_GLOBAL_DATA,
    DISPLAY_BAR_HEADER,
    ADD_INITIAL_VALUE,
    ADD_ADVISER_INFO,
    SET_NOTIFICATION_CONTENT,
    CHANGE_ADIVSER_FORM,
    SET_TOAST_MESSAGE,
    CHANGE_SEARCH_FORM,
    SET_CLOUD_PROFILE_DATA,
    SET_BILLING,
    SET_ACCOUNT_STATUS
};
